### ISSUE TITLE
Warnings when using plotting functions

### ISSUE THREAD

**Issue by eirini-zormpa** [OttaviaE/implicitMeasures#2]
I get the following warnings when using the `d_plot` function:
```
> d_plot(dscore)
Warning messages:
1: Use of `data$d_cres` is discouraged. Use `d_cres` instead. 
2: Use of `data$d` is discouraged. Use `d` instead. 
```
There are similar warnings for the `d_dist`, `multi_scores[[2]]`, and `multi_dsciat()` functions. This is not a big issue though, the plots are generated without problems!

#openjournals/joss-reviews#2297

**Comment by OttaviaE** [comment]
Hey @eirini-zormpa, yep, I know about that warning. To fix that, i should get rid of `data`, but when I do that and check the package with devtoos::check() I get a warning mesagge becasue the funtcion can't find the object d_cres (and this is true for all the the other graphical functions), even though the graphical representation are reproduced without problems. Since I submitted the package to CRAN, I needed it to have no warnings or notes, that's why I decided to keep it the way it is now!

**Comment by eirini-zormpa** [comment]
thanks that makes sense!

**Comment by wjakethompson** [comment]
Hi @OttaviaE!

You can get rid of the warnings by using the `.data` pronoun from [{rlang}](https://rlang.r-lib.org/reference/tidyeval-data.html) that is also exported by {ggplot2}, so no need for additional dependencies.

So within the `ggplot()` function, instead of using `data$d` you can use `.data$d`, and this will get rid of the warning. For example:

```r
d_graph <- ggplot(data,
                      aes(y = .data$d, x = .data$d_cres)) +
                      geom_point(col = col_point,
                      size = point_size)
```

If it's possible to make this change, I think it would be helpful. I agree with @eirini-zormpa that the warnings are a little confusing/worrisome when first running the plotting functions, as most users won't understand what is happening since they probably aren't looking at the source code.

**Comment by OttaviaE** [comment]
Thanks @wjakethompson, I'll do that for sure! Thank you for your al suggestions actually, I'll work on them ASAP and provide an appropriate answer under the specific thread =)
